version: "3.7"

services:

  notes-db:
    container_name: notes-db
    image: postgres:12.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # Persist data that is stored in db after
      # container is shutdown.
      - notes-db_data:/var/lib/postgresql/data/
    networks:
      - notes-net
    # ports:
    #   - "5432:5432"
  
  notes-api-develop:
    # container_name: notes-api
    hostname: notes-api
    profiles: 
      - develop
    develop:
      watch:
        - action: sync+restart
          path: ./apps
          target: /home/apps
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - JWT_SECRET_KEY=jta99001
      - POSTGRES_DB_HOST=notes-db
    depends_on:
      - notes-db
    # https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
    restart: unless-stopped
    networks:
      - notes-net
    ports:
      - "8000:8000"
    

  nginx-performer:
    container_name: nginx-performer
    build:
      context: nginx
      dockerfile: Dockerfile.develop
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
    restart: always
    networks:
      - notes-net
    ports:
      - "80:80"
    depends_on:
      - notes-db


volumes:
  notes-db_data:

networks:
  notes-net: